
import classes.DBO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sam
 */
public class DptMaster extends javax.swing.JInternalFrame {
String value;
DBO obj=new DBO();
int deptid=1;

    /**
     * Creates new form DptMaster
     */
    public DptMaster() {
        initComponents();
         setVisible(true);
      lb1.setVisible(false);
      ndptf.setVisible(false);
         updtbtn.setEnabled(false);
      list.setVisible(false);
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        dptf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        ndptf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        updtbtn = new javax.swing.JButton();
        srchbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        clsbtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Department Master");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        lb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb1.setText("New Dept Name");
        jPanel1.add(lb1);
        lb1.setBounds(40, 70, 99, 17);

        dptf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dptfKeyReleased(evt);
            }
        });
        jPanel1.add(dptf);
        dptf.setBounds(180, 30, 108, 20);

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 30, 120, 73);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Department Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 30, 113, 17);

        ndptf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ndptfKeyReleased(evt);
            }
        });
        jPanel1.add(ndptf);
        ndptf.setBounds(180, 70, 108, 20);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        updtbtn.setText("Update");
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        srchbtn.setText("Search");
        srchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbtnActionPerformed(evt);
            }
        });

        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        clsbtn.setText("Close");
        clsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(delbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updtbtn))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(srchbtn)
                    .addComponent(clsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(updtbtn)
                    .addComponent(srchbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbtn)
                    .addComponent(delbtn)
                    .addComponent(clsbtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsbtnActionPerformed

         int flag=   JOptionPane.showConfirmDialog(null,"Are you sure you want to close ?","Warning",JOptionPane.YES_NO_OPTION);
       if(flag==0)
       {
        setVisible(false);
       } // TODO add your handling code here:
    }//GEN-LAST:event_clsbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        value="add";
dptf.requestFocusInWindow();
updtbtn.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addbtnActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
int flag=1;
        if(value=="add"){
            flag=   JOptionPane.showConfirmDialog(null,"Are you sure you want to add this department ?","Warning",JOptionPane.YES_NO_OPTION);
        if(flag==0)
        {add();
        dptf.setText("");
        }
        }
        else
            if(value=="edit"){
                flag=   JOptionPane.showConfirmDialog(null,"Are you sure you want to update this department ?","Warning",JOptionPane.YES_NO_OPTION);
                if(flag==0)
                edit();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_updtbtnActionPerformed

    private void srchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbtnActionPerformed
value="search";
dptf.setEnabled(true);
dptf.setEditable(true);
dptf.setText("");
dptf.requestFocusInWindow();
editbtn.setEnabled(true);
delbtn.setEnabled(true);
addbtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_srchbtnActionPerformed

    private void dptfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dptfKeyReleased

        ArrayList dd=new ArrayList();
 int i=0;
 try
 {
 if(value.equals("search") && dptf.getText()!="")
 {
     String s="where [Dept Name] like '"+dptf.getText().concat("%")+"'";// and deptid="+deptid;
     dd=obj.searchDept(s);
     Object data[]=new Object[dd.size()];
     
     for(i=0;i<dd.size();i++)
     {
         data[i]=dd.get(i);
         
     }
     //JOptionPane.showMessageDialog(null,"Searching done");
     jScrollPane1.setVisible(true);
     list.setVisible(true);
     list.setListData(data);
     
    
 }
 }
 catch(Exception e)
 { }
 // TODO add your handling code here:
    }//GEN-LAST:event_dptfKeyReleased

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
try {
            String name=list.getSelectedValue().toString();
                   dptf.setText(name);
         dptf.setEditable(false);
                  //  JOptionPane.showMessageDialog(null,"Institute ID is "+deptid,"Done",JOptionPane.INFORMATION_MESSAGE);
                    // TODO add your handling code here:
        } catch (Exception ex) {
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_listMouseClicked

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed

          int flag=   JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this department ?","Warning",JOptionPane.YES_NO_OPTION);
       if(flag==0)
       {
        delete(); 
       } // TODO add your handling code here:
    }//GEN-LAST:event_delbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
updtbtn.setEnabled(true);
         lb1.setVisible(true);
      ndptf.setVisible(true);
      ndptf.requestFocusInWindow();
      value="edit"; 
      
        
        // TODO add your handling code here:
    }//GEN-LAST:event_editbtnActionPerformed

    private void ndptfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ndptfKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ndptfKeyReleased
 void delete()
{
    value="delete";
dptf.setEnabled(true);
dptf.setEditable(true);
dptf.requestFocusInWindow();
editbtn.setEnabled(true);
addbtn.setEnabled(false);
   if(chkBlank())
    {
      
        updtbtn.setEnabled(false);
        if(value.equals("delete"))
        {
            try
            {
                String s = obj.deleteDept(dptf.getText());
            
            
            if(s.equals("yes"))
            {
                JOptionPane.showMessageDialog(null,"Deleted","Done",JOptionPane.INFORMATION_MESSAGE);
           dptf.setText("");
           jScrollPane1.setVisible(false);
           list.setVisible(false);
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Not Deleted","Error",JOptionPane.ERROR_MESSAGE);
            }
            }
        catch(Exception e)
        {
        }
        }
    }

}
 
 void edit()
{
   
dptf.setEnabled(true);
dptf.setEditable(false);
//dptf.requestFocusInWindow();
editbtn.setEnabled(false);
addbtn.setEnabled(false);
   if(chkBlank())
    {
      
        updtbtn.setEnabled(false);
       
        {
            try
            {
                String s = obj.editDept(dptf.getText(),ndptf.getText());
            
            
            if(s.equals("yes"))
            {
                JOptionPane.showMessageDialog(null,"Updated Successfully","Done",JOptionPane.INFORMATION_MESSAGE);
           dptf.setText("");
           jScrollPane1.setVisible(false);
           list.setVisible(false);
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Not Updated","Error",JOptionPane.ERROR_MESSAGE);
            }
            ndptf.setText("");
            lb1.setVisible(false);
            ndptf.setVisible(false);
            addbtn.setEnabled(true);
            }
        catch(Exception e)
        {
        }
        }
    }

}
 
 
    void add()
{
    if(chkBlank())
    {
        dptf.setEnabled(true);
        updtbtn.setEnabled(false);
        
        {
            try
            {
                String s = obj.insertDept(dptf.getText());
            
            
            if(s.equals("yes"))
            {
                JOptionPane.showMessageDialog(null,"Inserted","Done",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Not Inserted","Error",JOptionPane.ERROR_MESSAGE);
            }
            }
        catch(Exception e)
        {
        }
        }
    }
}
  boolean chkBlank()
{
    if(dptf.getText().equals(""))
    {
        //lb.setText(""); 
        
        JOptionPane.showMessageDialog(null,"Please Fill Department Name","Warning",JOptionPane.WARNING_MESSAGE);
    return false;
    }
    
    else
{
return true;

}
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton clsbtn;
    private javax.swing.JButton delbtn;
    private javax.swing.JTextField dptf;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JList list;
    private javax.swing.JTextField ndptf;
    private javax.swing.JButton srchbtn;
    private javax.swing.JButton updtbtn;
    // End of variables declaration//GEN-END:variables
}
