
import classes.DBO;
import datechooser.model.multiple.PeriodSet;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sam
 */
public class EmpMaster extends javax.swing.JInternalFrame {

    String value = null;
    DBO obj = new DBO();
    double tchexp = 0, rschexp = 0;
    int srno = 0, fcid = 0, basicsal = 0, gradepaydp = 0, dap = 0, dar = 0, hrar = 0, ta = 0, othall = 0, grosssal = 0;
    String left, frdate, name, title, fname, mname, lname, dob, doj, sex, fthrname, mthrname, address, city, state,
            pstlcode, religion, caste, mobile, email, panno, adhcardno, desig, rank, prgrm, course, appt, salmode, doctrt, pgd,
            ugd, othqual, spec, payscale, paystype, bank, bbranch, ifsccode, bankacno, appttype, appltrno, handi, onleave, lvtype, olf, olu;
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");

    /**
     * Creates new form EmpMaster
     */
    public EmpMaster() {
        initComponents();
        fieldEnable(false);
        setVisible(true);
        editbtn.setEnabled(false);
        list.setVisible(false);
        list.setEnabled(false);
        jScrollPane1.setVisible(false);
        updtbtn.setEnabled(false);
        typelvcb.setEnabled(false);

        frddcc.setDateFormat(sdf);
        dobdcc.setDateFormat(sdf);
        dojdcc.setDateFormat(sdf);
        olfdcc.setDateFormat(sdf);
        oludcc.setDateFormat(sdf);
        olfdcc.setEnabled(false);
        oludcc.setEnabled(false);
        appolnotf.setEnabled(false);
        frddcc.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        updtbtn = new javax.swing.JButton();
        srchbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        clsbtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sntf = new javax.swing.JTextField();
        fcidtf = new javax.swing.JTextField();
        leftcb = new javax.swing.JComboBox();
        frddcc = new datechooser.beans.DateChooserCombo();
        nametf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mnametf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fnametf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lnametf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        titlecb = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        dobdcc = new datechooser.beans.DateChooserCombo();
        jLabel11 = new javax.swing.JLabel();
        dojdcc = new datechooser.beans.DateChooserCombo();
        jLabel12 = new javax.swing.JLabel();
        sexcb = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        fthrnametf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mthrnametf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addrtf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        citytf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        statecb = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        pstlcodetf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        relcb = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        castetf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        mobtf = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pantf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        adhctf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        desigtf = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        rankcb = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        progcb = new javax.swing.JComboBox();
        coursecb = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        appocb = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        salmodecb = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        doctcb = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        pgdtf = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        ugdtf = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        othqualtf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        spetf = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        texptf = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        rexptf = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        payscaletypecb = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        bsaltf = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        gpdtf = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        daptf = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        dartf = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        hratf = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        tatf = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        othalltf = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        gsaltf = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        bankcb = new javax.swing.JComboBox();
        jLabel49 = new javax.swing.JLabel();
        bbranchtf = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        ifsctf = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        baccnotf = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        appotypecb = new javax.swing.JComboBox();
        jLabel53 = new javax.swing.JLabel();
        appolnotf = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        handicb = new javax.swing.JComboBox();
        jLabel55 = new javax.swing.JLabel();
        fonlvcb = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        typelvcb = new javax.swing.JComboBox();
        jLabel57 = new javax.swing.JLabel();
        olfdcc = new datechooser.beans.DateChooserCombo();
        jLabel58 = new javax.swing.JLabel();
        oludcc = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        jLabel59 = new javax.swing.JLabel();
        payscalecb = new javax.swing.JComboBox();
        payscaletf = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Employee Master");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        updtbtn.setText("Update");
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        srchbtn.setText("Search");
        srchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbtnActionPerformed(evt);
            }
        });

        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        clsbtn.setText("Close");
        clsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsbtnActionPerformed(evt);
            }
        });

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updtbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(srchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(srchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sr. No.");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 20));

        jLabel2.setText("Faculty College ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, 30));

        jLabel4.setText("Faculty Relieved Date");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 120, 20));

        jLabel5.setText("Full Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 30));

        jLabel3.setText("Left the Institute?");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 110, 30));
        jPanel3.add(sntf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 60, -1));

        fcidtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcidtfActionPerformed(evt);
            }
        });
        fcidtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fcidtfKeyReleased(evt);
            }
        });
        jPanel3.add(fcidtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 150, -1));

        leftcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        leftcb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                leftcbItemStateChanged(evt);
            }
        });
        jPanel3.add(leftcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 30, 70, -1));

        frddcc.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    jPanel3.add(frddcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 120, -1));
    jPanel3.add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 270, -1));

    jLabel6.setText("First Name");
    jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 70, 30));
    jPanel3.add(mnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 130, -1));

    jLabel7.setText("Middle Name");
    jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 90, 30));
    jPanel3.add(fnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 120, -1));

    jLabel8.setText("Last Name");
    jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, 70, 30));
    jPanel3.add(lnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 120, -1));

    jLabel9.setText("Title");
    jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 40, 30));

    titlecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs", "Ms", "Dr." }));
    jPanel3.add(titlecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 50, -1));

    jLabel10.setText("Date of Birth");
    jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

    dobdcc.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
jPanel3.add(dobdcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 120, -1));

jLabel11.setText("Date of Joining");
jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 90, 20));

dojdcc.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
    new datechooser.view.appearance.ViewAppearance("custom",
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            true,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 255),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(128, 128, 128),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(255, 0, 0),
            false,
            false,
            new datechooser.view.appearance.swing.ButtonPainter()),
        (datechooser.view.BackRenderer)null,
        false,
        true)));
jPanel3.add(dojdcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 120, -1));

jLabel12.setText("Sex");
jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 40, 20));

sexcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
jPanel3.add(sexcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 90, -1));

jLabel13.setText("Father's Name");
jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 90, 30));
jPanel3.add(fthrnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 120, 170, -1));

jLabel14.setText("Mother's Name");
jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 90, 20));
jPanel3.add(mthrnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 160, -1));

jLabel15.setText("Address");
jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 173, 60, -1));
jPanel3.add(addrtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 170, 410, -1));

jLabel16.setText("City");
jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 173, 40, -1));
jPanel3.add(citytf, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 170, 90, -1));

jLabel17.setText("State");
jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 40, 30));

statecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Andaman and Nicobar", "Andra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadar and Nagar Haveli", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadeep", "Madya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Pondicherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttaranchal", "Uttar Pradesh", "West Bengal" }));
jPanel3.add(statecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 170, 180, -1));

jLabel18.setText("Postal Code");
jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 70, 30));
jPanel3.add(pstlcodetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 140, -1));

jLabel19.setText("Religion");
jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 218, 60, -1));

relcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hindu", "Jain", "Muslim", "Christian", "Sikh" }));
jPanel3.add(relcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 215, 120, -1));

jLabel20.setText("Caste");
jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 214, 40, 30));
jPanel3.add(castetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 215, 90, -1));

jLabel21.setText("Mobile");
jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 218, 40, -1));
jPanel3.add(mobtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 215, 150, -1));

jLabel22.setText("Email");
jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 218, 40, -1));
jPanel3.add(emailtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 215, 260, -1));

jLabel23.setText("PAN No.");
jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 214, 50, 30));
jPanel3.add(pantf, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 170, 30));

jLabel24.setText("Aadhar Card No");
jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 20));
jPanel3.add(adhctf, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 260, 210, -1));

jLabel25.setText("Designation");
jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 263, 70, 20));
jPanel3.add(desigtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 260, 210, -1));

jLabel26.setText("Rank");
jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 60, 30));

rankcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
jPanel3.add(rankcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 260, 40, -1));

jLabel27.setText("Programme");
jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 70, 20));

jLabel28.setText("Course");
jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 310, 60, -1));

progcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engineering and Technology", "Management Studies" }));
progcb.addItemListener(new java.awt.event.ItemListener() {
public void itemStateChanged(java.awt.event.ItemEvent evt) {
    progcbItemStateChanged(evt);
    }
    });
    jPanel3.add(progcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 250, -1));

    coursecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIRST YEAR/OTHER", "APPLIED SCIENCES", "COMPUTER SCIENCE AND ENGINEERING", "ELECTRONICS & COMMUNICATION ENGG", "MECHANICAL ENGINEERING", "CIVIL ENGINEERING", "BIOTECHNOLOGY" }));
    jPanel3.add(coursecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 305, 300, -1));

    jLabel29.setText("Appointment");
    jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 308, 70, -1));

    appocb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FT", "PT" }));
    jPanel3.add(appocb, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 305, 50, -1));

    jLabel30.setText("Salary Mode");
    jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 308, 70, -1));

    salmodecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Credit to Bank", "By Cheque", "Cash", "Net Transfer" }));
    jPanel3.add(salmodecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 305, 120, -1));

    jLabel31.setText("Doctorate");
    jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 308, 70, -1));

    doctcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
    jPanel3.add(doctcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 305, 60, -1));

    jLabel32.setText("PG Degree");
    jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 304, 70, 20));
    jPanel3.add(pgdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 140, -1));

    jLabel33.setText("UG Degree");
    jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 350, 80, 30));
    jPanel3.add(ugdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 351, 130, -1));

    jLabel34.setText("Other Qualification");
    jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 110, 30));
    jPanel3.add(othqualtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 140, -1));

    jLabel35.setText("Specialization");
    jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 80, 30));
    jPanel3.add(spetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 351, 180, -1));

    jLabel36.setText("Teaching Exp. (In Yrs)");
    jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 120, 30));
    jPanel3.add(texptf, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 50, -1));

    jLabel37.setText("Research Exp.");
    jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 80, 30));
    jPanel3.add(rexptf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 50, -1));

    jLabel38.setText("Pay Scale");
    jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, 30));

    jLabel39.setText("Pay Scale Type");
    jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 90, -1));

    payscaletypecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIth Pay Scale", "VIIth Pay Scale" }));
    jPanel3.add(payscaletypecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 395, 120, -1));

    jLabel40.setText("Basic Salary (In Rs.)");
    jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 120, 20));
    jPanel3.add(bsaltf, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 100, -1));

    jLabel41.setText("Grade Pay/ DP");
    jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 90, 20));
    jPanel3.add(gpdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 400, 90, -1));

    jLabel42.setText("DA %");
    jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 444, 40, -1));
    jPanel3.add(daptf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 441, 50, -1));

    jLabel43.setText("DA (In Rs.)");
    jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 444, 80, -1));
    jPanel3.add(dartf, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 441, 70, -1));

    jLabel44.setText("HRA (In Rs.)");
    jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 444, 80, -1));
    jPanel3.add(hratf, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 441, 80, -1));

    jLabel45.setText("T.A.");
    jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 40, 20));
    jPanel3.add(tatf, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 440, 70, -1));

    jLabel46.setText("Other Allowances (In Rs.)");
    jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 140, 20));
    jPanel3.add(othalltf, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 90, -1));

    jLabel47.setText("Gross Pay/ Month");
    jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, 110, 20));
    jPanel3.add(gsaltf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 120, -1));

    jLabel48.setText("Bank Name");
    jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 70, 20));

    bankcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oriental Bank of Commerce", "Allahabad Bank", "Andhra Bank", "Bank of Baroda", "Bank of India", "Bank of Maharashtra", "Canara Bank", "Central Bank of India", "HDFC Bank", "ICICI Bank", "Indian Bank", "Indian Overseas Bank", "Punjab & Sind Bank", "Punjab National Bank", "State Bank of India", "State Bank of Patiala", "Syndicate Bank", "UCO Bank", "Union Bank of India", "United Bank Of India", "Yes Bank" }));
    jPanel3.add(bankcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 300, 30));

    jLabel49.setText("Bank Branch Name");
    jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 130, 30));
    jPanel3.add(bbranchtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 340, -1));

    jLabel50.setText("IFSC Code");
    jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 90, 20));
    jPanel3.add(ifsctf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 130, -1));

    jLabel51.setText("Bank A/C No.");
    jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 532, 80, 20));
    jPanel3.add(baccnotf, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 529, 230, -1));

    jLabel52.setText("Appointment Type");
    jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 100, 20));

    appotypecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Approved" }));
    appotypecb.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            appotypecbItemStateChanged(evt);
        }
    });
    jPanel3.add(appotypecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 130, -1));

    jLabel53.setText("Approval Letter No.");
    jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 530, 110, 20));
    jPanel3.add(appolnotf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 210, -1));

    jLabel54.setText("Physically Handicapped");
    jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, 140, 30));

    handicb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
    jPanel3.add(handicb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, 70, -1));

    jLabel55.setText("Faculty on Leave");
    jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, 20));

    fonlvcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
    fonlvcb.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            fonlvcbItemStateChanged(evt);
        }
    });
    jPanel3.add(fonlvcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 60, -1));

    jLabel56.setText("Type of Leave");
    jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 80, 20));

    typelvcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Study", "Casual", "EOL/Maternity", "Duty", "Vacation", "Compensatory", "Half Day", "Academic" }));
    jPanel3.add(typelvcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 120, -1));

    jLabel57.setText("On Leave From");
    jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 90, 20));

    olfdcc.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
jPanel3.add(olfdcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 120, -1));

jLabel58.setText("On Leave Upto");
jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 90, 20));

oludcc.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
    new datechooser.view.appearance.ViewAppearance("custom",
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            true,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 255),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(128, 128, 128),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(255, 0, 0),
            false,
            false,
            new datechooser.view.appearance.swing.ButtonPainter()),
        (datechooser.view.BackRenderer)null,
        false,
        true)));
jPanel3.add(oludcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, 130, -1));

list.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
    listMouseClicked(evt);
    }
    });
    jScrollPane1.setViewportView(list);

    jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 150, 60));

    jLabel59.setText("Pay Scale");
    jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 400, 70, 30));

    payscalecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
    payscalecb.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            payscalecbItemStateChanged(evt);
        }
    });
    jPanel3.add(payscalecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 70, -1));
    jPanel3.add(payscaletf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 180, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(19, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(18, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsbtnActionPerformed


        int flag = JOptionPane.showConfirmDialog(null, "Are you sure you want to close ?", "Warning", JOptionPane.YES_NO_OPTION);
        if (flag == 0) {
            setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_clsbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        jScrollPane1.setVisible(false);
        list.setVisible(false);
        fieldClear();
        bbranchtf.setText("OBC BRANCH, NCCE, ISRANA");
        ifsctf.setText("ORBC0105220");
        fieldEnable(true);
        sntf.requestFocusInWindow();
        value = "add";

        updtbtn.setEnabled(true);
//  add your handling code here:
    }//GEN-LAST:event_addbtnActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed

        int flag = 1;
        if (value.equals("add")) {
            flag = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this record ?", "Warning", JOptionPane.YES_NO_OPTION);
        } else if (value.equals("edit")) {
            flag = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this record ?", "Warning", JOptionPane.YES_NO_OPTION);

        }
        if (flag == 0) {
            try {
                getValues();
                if (bsaltf.getText().equals("")) {
                    basicsal = 0;
                }
                if (gpdtf.getText().equals("")) {
                    gradepaydp = 0;
                }
                if (daptf.getText().equals("")) {
                    dap = 0;
                }
                if (dartf.getText().equals("")) {
                    dar = 0;
                }
                if (hratf.getText().equals("")) {
                    hrar = 0;
                }
                if (tatf.getText().equals("")) {
                    ta = 0;
                }
                if (othalltf.getText().equals("")) {
                    othall = 0;
                }
                if (gsaltf.getText().equals("")) {
                    grosssal = 0;
                }
                if (texptf.getText().equals("")) {
                    tchexp = 0.0;
                }
                if (rexptf.getText().equals("")) {
                    rschexp = 0.0;
                }
                if (!fonlvcb.getSelectedItem().toString().equals("Yes")) {
                    lvtype = "N/A";
                    olf = "N/A";
                    olu = "N/A";
                }
                if (!appolnotf.isEnabled()) {
                    appltrno = "N/A";
                }
                if (!frddcc.isEnabled()) {
                    frdate = "N/A";
                }
                if (chkBlank()) {
                    update();
                }
            } // TODO add your handling code here:
            catch (Exception ex) {
                Logger.getLogger(EmpMaster.class.getName()).log(Level.SEVERE, null, ex);
            }


        }
// TODO add your handling code here:
    }//GEN-LAST:event_updtbtnActionPerformed

    private void srchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbtnActionPerformed

        value = "search";
        fieldClear();
        fieldEnable(false);

        fcidtf.setEnabled(true);
        fcidtf.setEditable(true);
        fcidtf.requestFocusInWindow();
        editbtn.setEnabled(true);
        delbtn.setEnabled(true);
        addbtn.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_srchbtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed

        int flag = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this record ?", "Warning", JOptionPane.YES_NO_OPTION);
        if (flag == 0) {
            try {
                value = "delete";
                if (fcidtf.getText() != "") {
                    delete();
                }
                delbtn.setEnabled(false);
            } // TODO add your handling code here:
            catch (Exception ex) {
                Logger.getLogger(EmpMaster.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_delbtnActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        throw new UnsupportedOperationException("Not supported yet.");
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

        throw new UnsupportedOperationException("Not supported yet.");
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void fcidtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fcidtfKeyReleased

        ArrayList dd = new ArrayList();
        int i = 0;
        try {
            if (value.equals("search") && fcidtf.getText() != "") {
                String s = "where [Faculty College ID] like '" + fcidtf.getText().concat("%") + "'";
                dd = obj.searchEmp(s);
                Object data[] = new Object[dd.size()];

                for (i = 0; i < dd.size(); i++) {
                    data[i] = dd.get(i);

                }

                jScrollPane1.setVisible(true);
                list.setVisible(true);
                list.setEnabled(true);
                list.setListData(data);

            }
        } catch (Exception e) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_fcidtfKeyReleased

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        try {
            listClick();


        } catch (Exception ex) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_listMouseClicked

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        value = "edit";
        updtbtn.setEnabled(true);
        delbtn.setEnabled(false);
        addbtn.setEnabled(false);
        fieldEnable(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_editbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed

        /* if(value.equals("view"))
         {
         if(fcidtf.getText().equals(""))
         {
         JOptionPane.showMessageDialog(null,"Enter the Faculty College ID","Warning",JOptionPane.WARNING_MESSAGE);
          
         }
         else
         view();
         }
         else */
        {
            value = "view";
            fieldClear();
            fieldEnable(false);
            fcidtf.setEditable(true);
            fcidtf.requestFocusInWindow();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbtnActionPerformed

    private void fcidtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcidtfActionPerformed

        if (fcidtf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter the Faculty College ID", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            try {
                //  dojdcc.setEnabled(true);
                view();
            } catch (Exception ex) {
                Logger.getLogger(EmpMaster.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fcidtfActionPerformed

    private void payscalecbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_payscalecbItemStateChanged
        if (payscalecb.getSelectedItem().toString().equals("No")) {
            payscale = "N/A";
            paystype = "N/A";
            payscaletf.setEnabled(false);
            payscaletypecb.setEnabled(false);

            gpdtf.setEnabled(false);
            daptf.setEnabled(false);
            gradepaydp = 0;
            dap = 0;
        } else {
            payscaletf.setEnabled(true);
            payscaletypecb.setEnabled(true);

            gpdtf.setEnabled(true);
            daptf.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_payscalecbItemStateChanged

    private void fonlvcbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fonlvcbItemStateChanged

        if (fonlvcb.getSelectedItem().toString().equals("Yes")) {
            typelvcb.setEnabled(true);
            olfdcc.setEnabled(true);
            oludcc.setEnabled(true);
        } else {
            typelvcb.setEnabled(false);
            olfdcc.setEnabled(false);
            oludcc.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_fonlvcbItemStateChanged

    private void appotypecbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_appotypecbItemStateChanged

        if (appotypecb.getSelectedItem().toString().equals("Approved")) {
            appolnotf.setEnabled(true);
        } else {
            appolnotf.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_appotypecbItemStateChanged

    private void progcbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_progcbItemStateChanged

        if (progcb.getSelectedItem().toString().equals("Management Studies")) {
            coursecb.removeAllItems();

            coursecb.addItem("BACHELORS IN BUSINESS ADMINISTRATION");
            coursecb.addItem("BACHELORS IN COMPUTER APPLICATION");
            coursecb.addItem("MASTERS IN BUSINESS ADMINISTRATION");
            coursecb.addItem("MASTERS IN COMPUTER APPLICATION");
        } else {
            coursecb.removeAllItems();
            coursecb.addItem("FIRST YEAR/OTHER");
            coursecb.addItem("APPLIED SCIENCES");
            coursecb.addItem("COMPUTER SCIENCE AND ENGINEERING");
            coursecb.addItem("ELECTRONICS & COMMUNICATION ENGG");
            coursecb.addItem("MECHANICAL ENGINEERING");
            coursecb.addItem("CIVIL ENGINEERING");
            coursecb.addItem("BIOTECHNOLOGY");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_progcbItemStateChanged

    private void leftcbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_leftcbItemStateChanged

        if (leftcb.getSelectedItem().toString().equals("Yes")) {
            frddcc.setEnabled(true);
        } else {
            frddcc.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_leftcbItemStateChanged

    void getValues() throws Exception {
        try {
            if (!sntf.getText().equals("")) {
                srno = Integer.parseInt(sntf.getText());
            }
            if (!fcidtf.getText().equals("")) {
                fcid = Integer.parseInt(fcidtf.getText());
            }
            left = leftcb.getSelectedItem().toString();
            frdate = frddcc.getSelectedPeriodSet().toString(sdf);
            name = nametf.getText();
            title = titlecb.getSelectedItem().toString();
            fname = fnametf.getText();
            mname = mnametf.getText();
            lname = lnametf.getText();
            dob = dobdcc.getSelectedPeriodSet().toString(sdf);
            doj = dojdcc.getSelectedPeriodSet().toString(sdf);
            sex = sexcb.getSelectedItem().toString();
            fthrname = fthrnametf.getText();
            mthrname = mthrnametf.getText();
            address = addrtf.getText();
            city = citytf.getText();
            state = statecb.getSelectedItem().toString();
            pstlcode = pstlcodetf.getText();
            religion = relcb.getSelectedItem().toString();
            caste = castetf.getText();
            mobile = mobtf.getText();
            email = emailtf.getText();
            panno = pantf.getText();
            adhcardno = adhctf.getText();
            desig = desigtf.getText();
            rank = rankcb.getSelectedItem().toString();
            prgrm = progcb.getSelectedItem().toString();
            course = coursecb.getSelectedItem().toString();
            appt = appocb.getSelectedItem().toString();
            salmode = salmodecb.getSelectedItem().toString();
            doctrt = doctcb.getSelectedItem().toString();
            pgd = pgdtf.getText();
            ugd = ugdtf.getText();
            othqual = othqualtf.getText();
            spec = spetf.getText();
            if (!texptf.getText().equals("")) {
                tchexp = Double.parseDouble(texptf.getText());
            }
            if (!rexptf.getText().equals("")) {
                rschexp = Double.parseDouble(rexptf.getText());
            }
            payscale = payscaletf.getText();
            paystype = payscaletypecb.getSelectedItem().toString();
            if (!bsaltf.getText().equals("")) {
                basicsal = Integer.parseInt(bsaltf.getText());
            }
            if (gpdtf.isEnabled()) {
                if (!gpdtf.getText().equals("")) {
                    gradepaydp = Integer.parseInt(gpdtf.getText());
                }
            }
            if (daptf.isEnabled()) {
                if (!daptf.getText().equals("")) {
                    dap = Integer.parseInt(daptf.getText());
                }
            }
            if (!dartf.getText().equals("")) {
                dar = Integer.parseInt(dartf.getText());
            }
            if (!hratf.getText().equals("")) {
                hrar = Integer.parseInt(hratf.getText());
            }
            if (!tatf.getText().equals("")) {
                ta = Integer.parseInt(tatf.getText());
            }
            if (!othalltf.getText().equals("")) {
                othall = Integer.parseInt(othalltf.getText());
            }
            if (!gsaltf.getText().equals("")) {
                grosssal = Integer.parseInt(gsaltf.getText());
            }
            bank = bankcb.getSelectedItem().toString();
            bbranch = bbranchtf.getText();
            ifsccode = ifsctf.getText();
            bankacno = baccnotf.getText();
            appttype = appotypecb.getSelectedItem().toString();
            appltrno = appolnotf.getText();
            handi = handicb.getSelectedItem().toString();
            onleave = fonlvcb.getSelectedItem().toString();
            if (typelvcb.isEnabled()) {
                lvtype = typelvcb.getSelectedItem().toString();
            }
            if (olfdcc.isEnabled()) {
                olf = olfdcc.getSelectedPeriodSet().toString(sdf);
            }
            if (oludcc.isEnabled()) {
                olu = oludcc.getSelectedPeriodSet().toString(sdf);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmpMaster.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    void listClick() throws Exception {
        try {


            ArrayList eal = new ArrayList();

            String name = list.getSelectedValue().toString();

            fcidtf.setText(name);
            int fci = Integer.parseInt(name);
            String sql = "where [Faculty College ID]=" + fci;
            eal = obj.empSelect(sql);
            int i = 0;

            sntf.setText(eal.get(i).toString());
            fcidtf.setText(eal.get(++i).toString());
            leftcb.setSelectedItem(eal.get(++i).toString());

            Object dta = eal.get(++i);
            String frdt = dta.toString();
            if (!frdt.equals("N/A")) {
                Date date = (Date) sdf.parse(frdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                frddcc.setSelectedDate(cal);
            }

            nametf.setText(eal.get(++i).toString());
            titlecb.setSelectedItem(eal.get(++i).toString());
            fnametf.setText(eal.get(++i).toString());
            mnametf.setText(eal.get(++i).toString());
            lnametf.setText(eal.get(++i).toString());

            Object dtb = eal.get(++i);
            String dobdt = dtb.toString();
            if (!dobdt.equals("N/A")) {
                Date date = (Date) sdf.parse(dobdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                dobdcc.setSelectedDate(cal);
            }

            Object dtc = eal.get(++i);
            String dojdt = dtc.toString();
            if (!dojdt.equals("N/A")) {
                Date date = (Date) sdf.parse(dojdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                dojdcc.setSelectedDate(cal);
            }

            sexcb.setSelectedItem(eal.get(++i).toString());
            fthrnametf.setText(eal.get(++i).toString());
            mthrnametf.setText(eal.get(++i).toString());
            addrtf.setText(eal.get(++i).toString());
            citytf.setText(eal.get(++i).toString());
            statecb.setSelectedItem(eal.get(++i).toString());
            pstlcodetf.setText(eal.get(++i).toString());
            relcb.setSelectedItem(eal.get(++i).toString());
            castetf.setText(eal.get(++i).toString());
            mobtf.setText(eal.get(++i).toString());
            emailtf.setText(eal.get(++i).toString());
            pantf.setText(eal.get(++i).toString());
            adhctf.setText(eal.get(++i).toString());
            desigtf.setText(eal.get(++i).toString());
            rankcb.setSelectedItem(eal.get(++i).toString());
            progcb.setSelectedItem(eal.get(++i).toString());
            coursecb.setSelectedItem(eal.get(++i).toString());
            appocb.setSelectedItem(eal.get(++i).toString());
            salmodecb.setSelectedItem(eal.get(++i).toString());
            doctcb.setSelectedItem(eal.get(++i).toString());
            pgdtf.setText(eal.get(++i).toString());
            ugdtf.setText(eal.get(++i).toString());
            othqualtf.setText(eal.get(++i).toString());
            spetf.setText(eal.get(++i).toString());
            texptf.setText(eal.get(++i).toString());
            rexptf.setText(eal.get(++i).toString());
            payscaletf.setText(eal.get(++i).toString());
            payscaletypecb.setSelectedItem(eal.get(++i).toString());
            bsaltf.setText(eal.get(++i).toString());
            gpdtf.setText(eal.get(++i).toString());
            daptf.setText(eal.get(++i).toString());
            dartf.setText(eal.get(++i).toString());
            hratf.setText(eal.get(++i).toString());
            tatf.setText(eal.get(++i).toString());
            othalltf.setText(eal.get(++i).toString());
            gsaltf.setText(eal.get(++i).toString());
            bankcb.setSelectedItem(eal.get(++i).toString());
            bbranchtf.setText(eal.get(++i).toString());
            ifsctf.setText(eal.get(++i).toString());
            baccnotf.setText(eal.get(++i).toString());
            appotypecb.setSelectedItem(eal.get(++i).toString());
            appolnotf.setText(eal.get(++i).toString());
            handicb.setSelectedItem(eal.get(++i).toString());
            fonlvcb.setSelectedItem(eal.get(++i).toString());
            typelvcb.setSelectedItem(eal.get(++i).toString());

            Object dtd = eal.get(++i);
            String olfdt = dtd.toString();
            if (!olfdt.equals("N/A")) {
                Date date = (Date) sdf.parse(olfdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                olfdcc.setSelectedDate(cal);
            }

            Object dte = eal.get(++i);
            String oludt = dte.toString();
            if (!oludt.equals("N/A")) {
                Date date = (Date) sdf.parse(oludt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                oludcc.setSelectedDate(cal);
            }

            fieldEnable(false);
            addbtn.setEnabled(false);
            updtbtn.setEnabled(false);
            editbtn.setEnabled(true);
            delbtn.setEnabled(true);
            list.setVisible(false);
            jScrollPane1.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    void fieldEnable(boolean a) {

        sntf.setEditable(a);
        fcidtf.setEditable(a);
        leftcb.setEnabled(a);
//frddcc.setEnabled(a);
        nametf.setEditable(a);
        titlecb.setEnabled(a);
        fnametf.setEditable(a);
        mnametf.setEditable(a);
        lnametf.setEditable(a);
//dobdcc.setEnabled(a);
//dojdcc.setEnabled(a);
        sexcb.setEnabled(a);
        fthrnametf.setEditable(a);
        mthrnametf.setEditable(a);
        addrtf.setEditable(a);
        citytf.setEditable(a);
        statecb.setEnabled(a);
        pstlcodetf.setEditable(a);
        relcb.setEnabled(a);
        castetf.setEditable(a);
        mobtf.setEditable(a);
        emailtf.setEditable(a);
        pantf.setEditable(a);
        adhctf.setEditable(a);
        desigtf.setEditable(a);
        rankcb.setEnabled(a);
        progcb.setEnabled(a);
        coursecb.setEnabled(a);
        appocb.setEnabled(a);
        salmodecb.setEnabled(a);
        doctcb.setEnabled(a);
        pgdtf.setEditable(a);
        ugdtf.setEditable(a);
        othqualtf.setEditable(a);
        spetf.setEditable(a);
        texptf.setEditable(a);
        rexptf.setEditable(a);
        payscaletf.setEditable(a);
        payscalecb.setEnabled(a);
        payscaletypecb.setEnabled(a);
        bsaltf.setEditable(a);
        gpdtf.setEditable(a);
        daptf.setEditable(a);
        dartf.setEditable(a);
        hratf.setEditable(a);
        tatf.setEditable(a);
        othalltf.setEditable(a);
        gsaltf.setEditable(a);
        bankcb.setEnabled(a);
        bbranchtf.setEditable(a);
        ifsctf.setEditable(a);
        baccnotf.setEditable(a);
        appotypecb.setEnabled(a);
//appolnotf.setEditable(a);
        handicb.setEnabled(a);
        fonlvcb.setEnabled(a);
        /*typelvcb.setEnabled(a);
         olfdcc.setEnabled(a);
         oludcc.setEnabled(a);     */

    }

    void fieldClear() {
        sntf.setText("");
        fcidtf.setText("");
        leftcb.setSelectedIndex(0);
//frddcc.setEnabled(a);
        nametf.setText("");
        titlecb.setSelectedIndex(0);
        fnametf.setText("");
        mnametf.setText("");
        lnametf.setText("");
//dobdcc.removeAll();
//dojdcc.removeAll();
        sexcb.setSelectedIndex(0);
        fthrnametf.setText("");
        mthrnametf.setText("");
        addrtf.setText("");
        citytf.setText("");
        statecb.setSelectedIndex(0);
        pstlcodetf.setText("");
        relcb.setSelectedIndex(0);
        castetf.setText("");
        mobtf.setText("");
        emailtf.setText("");
        pantf.setText("");
        adhctf.setText("");
        desigtf.setText("");
        rankcb.setSelectedIndex(0);
        progcb.setSelectedIndex(0);
        coursecb.setSelectedIndex(0);
        appocb.setSelectedIndex(0);
        salmodecb.setSelectedIndex(0);
        doctcb.setSelectedIndex(0);
        pgdtf.setText("");
        ugdtf.setText("");
        othqualtf.setText("");
        spetf.setText("");
        texptf.setText("");
        rexptf.setText("");
        payscaletf.setText("");
        payscaletypecb.setSelectedIndex(0);
        bsaltf.setText("");
        gpdtf.setText("");
        daptf.setText("");
        dartf.setText("");
        hratf.setText("");
        tatf.setText("");
        othalltf.setText("");
        gsaltf.setText("");
        bankcb.setSelectedIndex(0);
        bbranchtf.setText("");
        ifsctf.setText("");
        baccnotf.setText("");
        appotypecb.setSelectedIndex(0);
        appolnotf.setText("");
        handicb.setSelectedIndex(0);
        fonlvcb.setSelectedIndex(0);
        typelvcb.setSelectedIndex(0);

//olfdcc.setEnabled(a);
//oludcc.setEnabled(a);




    }

    void delete() throws Exception {

        if (value.equals("delete")) {
            try {
                String s = obj.deleteEmp(Integer.parseInt(fcidtf.getText()));

                if (s.equals("yes")) {
                    JOptionPane.showMessageDialog(null, "Deleted", "Done", JOptionPane.INFORMATION_MESSAGE);
                    list.setVisible(false);
                    jScrollPane1.setVisible(false);
                    fcidtf.setText("");
                    fieldClear();
                    fieldEnable(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Not Deleted", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
            }

        }

    }

    void view() throws Exception {
        try {
            ArrayList eal = new ArrayList();

            int fci = Integer.parseInt(fcidtf.getText());
            String sql = "where [Faculty College ID]=" + fci;
            eal = obj.empSelect(sql);
            int i = 0;

            sntf.setText(eal.get(i).toString());
            fcidtf.setText(eal.get(++i).toString());
            leftcb.setSelectedItem(eal.get(++i).toString());

            Object dta = eal.get(++i);
            String frdt = dta.toString();
            if (!frdt.equals("N/A")) {
                Date date = (Date) sdf.parse(frdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                frddcc.setSelectedDate(cal);
            }

            nametf.setText(eal.get(++i).toString());
            titlecb.setSelectedItem(eal.get(++i).toString());
            fnametf.setText(eal.get(++i).toString());
            mnametf.setText(eal.get(++i).toString());
            lnametf.setText(eal.get(++i).toString());

            Object dtb = eal.get(++i);
            String dobdt = dtb.toString();
            if (!dobdt.equals("N/A")) {
                Date date = (Date) sdf.parse(dobdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                dobdcc.setSelectedDate(cal);
            }

            Object dtc = eal.get(++i);
            String dojdt = dtc.toString();
            if (!dojdt.equals("N/A")) {
                Date date = (Date) sdf.parse(dojdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                dojdcc.setSelectedDate(cal);
            }

            sexcb.setSelectedItem(eal.get(++i).toString());
            fthrnametf.setText(eal.get(++i).toString());
            mthrnametf.setText(eal.get(++i).toString());
            addrtf.setText(eal.get(++i).toString());
            citytf.setText(eal.get(++i).toString());
            statecb.setSelectedItem(eal.get(++i).toString());
            pstlcodetf.setText(eal.get(++i).toString());
            relcb.setSelectedItem(eal.get(++i).toString());
            castetf.setText(eal.get(++i).toString());
            mobtf.setText(eal.get(++i).toString());
            emailtf.setText(eal.get(++i).toString());
            pantf.setText(eal.get(++i).toString());
            adhctf.setText(eal.get(++i).toString());
            desigtf.setText(eal.get(++i).toString());
            rankcb.setSelectedItem(eal.get(++i).toString());
            progcb.setSelectedItem(eal.get(++i).toString());
            coursecb.setSelectedItem(eal.get(++i).toString());
            appocb.setSelectedItem(eal.get(++i).toString());
            salmodecb.setSelectedItem(eal.get(++i).toString());
            doctcb.setSelectedItem(eal.get(++i).toString());
            pgdtf.setText(eal.get(++i).toString());
            ugdtf.setText(eal.get(++i).toString());
            othqualtf.setText(eal.get(++i).toString());
            spetf.setText(eal.get(++i).toString());
            texptf.setText(eal.get(++i).toString());
            rexptf.setText(eal.get(++i).toString());
            payscaletf.setText(eal.get(++i).toString());
            payscaletypecb.setSelectedItem(eal.get(++i).toString());
            bsaltf.setText(eal.get(++i).toString());
            gpdtf.setText(eal.get(++i).toString());
            daptf.setText(eal.get(++i).toString());
            dartf.setText(eal.get(++i).toString());
            hratf.setText(eal.get(++i).toString());
            tatf.setText(eal.get(++i).toString());
            othalltf.setText(eal.get(++i).toString());
            gsaltf.setText(eal.get(++i).toString());
            bankcb.setSelectedItem(eal.get(++i).toString());
            bbranchtf.setText(eal.get(++i).toString());
            ifsctf.setText(eal.get(++i).toString());
            baccnotf.setText(eal.get(++i).toString());
            appotypecb.setSelectedItem(eal.get(++i).toString());
            appolnotf.setText(eal.get(++i).toString());
            handicb.setSelectedItem(eal.get(++i).toString());
            fonlvcb.setSelectedItem(eal.get(++i).toString());
            typelvcb.setSelectedItem(eal.get(++i).toString());

            Object dtd = eal.get(++i);
            String olfdt = dtd.toString();
            if (!olfdt.equals("N/A")) {
                Date date = (Date) sdf.parse(olfdt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                olfdcc.setSelectedDate(cal);
            }

            Object dte = eal.get(++i);
            String oludt = dte.toString();
            if (!oludt.equals("N/A")) {
                Date date = (Date) sdf.parse(oludt);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                oludcc.setSelectedDate(cal);
            }



            fieldEnable(false);
            addbtn.setEnabled(false);
            updtbtn.setEnabled(false);
            editbtn.setEnabled(true);
            delbtn.setEnabled(true);

        } catch (Exception ex) {
            Logger.getLogger(EmpMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update() throws Exception {
        if (value.equals("add")) {

            try {

                String s = obj.insertEmp(
                        srno, fcid, left, frdate, name, title, fname, mname, lname, dob, doj, sex, fthrname, mthrname, address, city, state, pstlcode, religion, caste, mobile, email, panno, adhcardno, desig, rank, prgrm, course, appt, salmode, doctrt, pgd, ugd, othqual, spec, tchexp, rschexp, payscale, paystype, basicsal, gradepaydp, dap, dar, hrar, ta, othall, grosssal, bank, bbranch, ifsccode, bankacno, appttype, appltrno, handi, onleave, lvtype, olf, olu);



                if (s.equals("yes")) {
                    JOptionPane.showMessageDialog(null, "Inserted", "Done", JOptionPane.INFORMATION_MESSAGE);
                    fieldClear();
                    fieldEnable(false);
                    delbtn.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Not Inserted", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
            }

        } else if (value.equals("edit")) {

            try {

                String s = obj.updateEmp(fcid, srno, fcid, left, frdate, name, title, fname, mname, lname, dob, doj, sex, fthrname, mthrname, address, city, state, pstlcode, religion, caste, mobile, email, panno, adhcardno, desig, rank, prgrm, course, appt, salmode, doctrt, pgd, ugd, othqual, spec, tchexp, rschexp, payscale, paystype, basicsal, gradepaydp, dap, dar, hrar, ta, othall, grosssal, bank, bbranch, ifsccode, bankacno, appttype, appltrno, handi, onleave, lvtype, olf, olu);

                if (s.equals("yes")) {
                    JOptionPane.showMessageDialog(null, "Updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                    fieldClear();
                    fieldEnable(false);
                    delbtn.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Not Updated", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
        updtbtn.setEnabled(false);
    }

    public boolean chkBlank() throws Exception {

        /* if(sntf.getText().equals("") || fcidtf.getText().equals("") || texptf.getText().equals("") || rexptf.getText().equals("") || bsaltf.getText().equals("") || gpdtf.getText().equals("") || daptf.getText().equals("") || dartf.getText().equals("") || hratf.getText().equals("") || tatf.getText().equals("") || othalltf.getText().equals("") || gsaltf.getText().equals("") || 
         left.equals("") || frdate.equals("") || name.equals("") || title.equals("") || fname.equals("") || mname.equals("") || lname.equals("") || dob.equals("") || doj.equals("") || sex.equals("") || fthrname.equals("") || mthrname.equals("") || address.equals("") || city.equals("") || state.equals("") || 
         pstlcode.equals("") || religion.equals("") || caste.equals("") || mobile.equals("") || email.equals("") || panno.equals("") || adhcardno.equals("") || desig.equals("") || rank.equals("") || prgrm.equals("") || course.equals("") || appt.equals("") || salmode.equals("") || doctrt.equals("") || pgd.equals("") || 
         ugd.equals("") || othqual.equals("") || spec.equals("") || payscale.equals("") || paystype.equals("") || bank.equals("") || bbranch.equals("") || ifsccode.equals("") || bankacno.equals("") ||  appttype.equals("") || appltrno.equals("") || handi.equals("") || onleave.equals("") || lvtype.equals("") || olf.equals("") || olu.equals("") && payscaletf.isEnabled())
         false){
         */

        if (fcidtf.getText().equals("") || nametf.getText().equals("") || fnametf.getText().equals("") || mnametf.getText().equals("") || lnametf.getText().equals("") || fthrnametf.getText().equals("") || mthrnametf.getText().equals("") || addrtf.getText().equals("") || citytf.getText().equals("") || pstlcodetf.getText().equals("") || castetf.getText().equals("") || mobtf.getText().equals("") || emailtf.getText().equals("") || desigtf.getText().equals("") || pgdtf.getText().equals("") || ugdtf.getText().equals("") || bbranchtf.getText().equals("") || baccnotf.getText().equals("") || (appotypecb.getSelectedItem().toString().equals("Approved") && appolnotf.getText().equals("")) || (payscalecb.getSelectedItem().toString().equals("Yes") && payscaletf.getText().equals(""))) {

            JOptionPane.showMessageDialog(null, "Please Fill All The Details", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField addrtf;
    private javax.swing.JTextField adhctf;
    private javax.swing.JComboBox appocb;
    private javax.swing.JTextField appolnotf;
    private javax.swing.JComboBox appotypecb;
    private javax.swing.JTextField baccnotf;
    private javax.swing.JComboBox bankcb;
    private javax.swing.JTextField bbranchtf;
    private javax.swing.JTextField bsaltf;
    private javax.swing.JTextField castetf;
    private javax.swing.JTextField citytf;
    private javax.swing.JButton clsbtn;
    private javax.swing.JComboBox coursecb;
    private javax.swing.JTextField daptf;
    private javax.swing.JTextField dartf;
    private javax.swing.JButton delbtn;
    private javax.swing.JTextField desigtf;
    private datechooser.beans.DateChooserCombo dobdcc;
    private javax.swing.JComboBox doctcb;
    private datechooser.beans.DateChooserCombo dojdcc;
    private javax.swing.JButton editbtn;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField fcidtf;
    private javax.swing.JTextField fnametf;
    private javax.swing.JComboBox fonlvcb;
    private datechooser.beans.DateChooserCombo frddcc;
    private javax.swing.JTextField fthrnametf;
    private javax.swing.JTextField gpdtf;
    private javax.swing.JTextField gsaltf;
    private javax.swing.JComboBox handicb;
    private javax.swing.JTextField hratf;
    private javax.swing.JTextField ifsctf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox leftcb;
    private javax.swing.JList list;
    private javax.swing.JTextField lnametf;
    private javax.swing.JTextField mnametf;
    private javax.swing.JTextField mobtf;
    private javax.swing.JTextField mthrnametf;
    private javax.swing.JTextField nametf;
    private datechooser.beans.DateChooserCombo olfdcc;
    private datechooser.beans.DateChooserCombo oludcc;
    private javax.swing.JTextField othalltf;
    private javax.swing.JTextField othqualtf;
    private javax.swing.JTextField pantf;
    private javax.swing.JComboBox payscalecb;
    private javax.swing.JTextField payscaletf;
    private javax.swing.JComboBox payscaletypecb;
    private javax.swing.JTextField pgdtf;
    private javax.swing.JComboBox progcb;
    private javax.swing.JTextField pstlcodetf;
    private javax.swing.JComboBox rankcb;
    private javax.swing.JComboBox relcb;
    private javax.swing.JTextField rexptf;
    private javax.swing.JComboBox salmodecb;
    private javax.swing.JComboBox sexcb;
    private javax.swing.JTextField sntf;
    private javax.swing.JTextField spetf;
    private javax.swing.JButton srchbtn;
    private javax.swing.JComboBox statecb;
    private javax.swing.JTextField tatf;
    private javax.swing.JTextField texptf;
    private javax.swing.JComboBox titlecb;
    private javax.swing.JComboBox typelvcb;
    private javax.swing.JTextField ugdtf;
    private javax.swing.JButton updtbtn;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
